/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMA_H_RPCGEN
#define _TEMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	char *command;
	char *word;
	int letters;
};
typedef struct message message;

#define MYRPC 0x20000044
#define MYRPCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_message 1
extern  char ** send_message_1(message *, CLIENT *);
extern  char ** send_message_1_svc(message *, struct svc_req *);
extern int myrpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_message 1
extern  char ** send_message_1();
extern  char ** send_message_1_svc();
extern int myrpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEMA_H_RPCGEN */
