/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema.h"

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->command, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->word, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->letters))
		 return FALSE;
	return TRUE;
}
